language: node_js
node_js:
  - 4.4.4

env:
  global:
  - secure: "o36U51ClABOoqHTeu6QwISbE6Ijm9oUiSo1v/Em/JLD0EylhpkI6iRY1Vgrr9DneUo3aU2sch21eNcQ6xbJx0c6qowJdvzNHAL/SnDTw+dKDDjitXNL9wmcNlzNRkHEEbiHwNup6wNwGqqzMVcCpt4mj7w8sT4+tAGPwFb2rCSgaGSrQrwTph85RUemNeEXide+1xpQFx4mmUZN6QbWXxqmGDCVWJd145RRfA+OFc0t5ASFi9k6crrMMRZJC9Kq2DB2CP7BI/j/5rl7H9kMPwWyJwyTp9LLrgvzfjHR6ofzXlMw9jATFuyljw516DpfrOzrQm12AhEF35M2jh/oGlcbV2Ocjmz+EgRbMdY5jOwxuiq7ehM7nhOOusZU8rHuiDvQYfleGyl8owhemFPRYBC6cbBTPhLfcRLwnirIWVoStnqiKATrrrpRvSSm+/Sr39KWAwzxtTlO2gZ++lHDgSuSA1KxmNxXgeLGP+xW6H8WVkozWFwhlaUISpE+hw9P5jFR6nY54FjZETKgr0hcuS/GdRSck6Hjc02m99onB7oFnfyeeJiVXYqqCuSNX+t8CX6C/v3qODkxR6fm7HWVu8zwTb7h8TPDh3m1s1i/DLUWwEO33NqXD2kADU98RqRsKNSCtDjku46xd/TGBnfKrU+hmXk0mhKYczRQdgKdVlCA="

install:
- npm install -g harp@0.20.3

script:
- pushd _src && harp compile --output .. && popd

after_success: >
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST;
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    # Configure Git with Travis CI information
    git config --global user.email "travis@travis-ci.org" ;
    git config --global user.name "travis-ci" ;
    # Delete the current repository
    rm -rf .git ;
    # Rebuild the repository from the generated files and push to GitHub pages
    git init ;
    git add . ;
    git commit -m "Deploy Travis CI build $TRAVIS_BUILD_NUMBER to GitHub pages" ;
    git push -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} master:gh-pages ;
  fi
